interface Asset {
  ID: number,
  type: 'Stock' | 'ETF' | 'Fund' | 'Bond' | 'Crypto' | 'Commodity' | 'RealEstate' | 'CashEquivalent',
  name: string,
  symbol: string,
  isin: string,
  kgv?: string,
  is_watched?: boolean,
  current_shares?: float,
  current_shares_before_ex_date?: float,
  current_invest?: float,
  current_sum_in_out?: float,
  price?: float,
  avg_price_paid?: float,
  currencySymbol?: string,
  quote?: import('../../utils/quoteMetadata').QuoteMetadata,
  bondHolding?: import('../../utils/bondHoldings').BondHolding,
  current_profit_loss?: float,
  current_profit_loss_percentage?: float,
  current_profit_loss_percentage_formatted?: string,
  dividends?: import('../../utils/dividendForecasts').DividendForecast[],
  dividendForecastError?: string,
  dividendForecastRequested?: boolean,
  dividends_earned?: float,
  exDividendDate?: string,
  payDividendDate?: string,
  dividendFrequency?: string,
  dividendYield?: float,
  next_estimated_dividend_per_share?: float
}
